import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface SignalFlip {
  signalId: string;
  signalName: string;
  from: number;
  to: number;
  direction: "bullish" | "bearish";
}

const SIGNAL_NAMES: Record<string, string> = {
  "yield-curve": "Yield Curve (2s10s)",
  "credit-spreads": "Credit Spreads (HY)",
  "breadth": "Market Breadth",
  "insider": "Insider Activity",
  "m2": "Money Supply (M2)",
  "vix": "VIX",
  "pmi": "CFNAI",
  "dxy": "Dollar (DXY)",
  "oil": "Oil (WTI)",
  "inflation": "Inflation Pass-Through",
  "earnings": "EPS Trends",
  "cadusd": "CAD/USD",
  "sentiment": "Consumer Sentiment",
  "seasonality": "Seasonality",
  "nfci": "Financial Conditions (NFCI)",
  "cb-liquidity": "CB Balance Sheets",
  "jobless-claims": "Initial Jobless Claims",
  "real-yield": "10-yr Real Yield (TIPS)",
  "lei": "Conference Board LEI",
  "ig-spreads": "IG Credit Spreads",
  "rate-path": "Rate Path (2Y–FFR)",
};

function scoreLabel(score: number): string {
  if (score > 0) return "bullish";
  if (score < 0) return "bearish";
  return "neutral";
}

function formatAlertEmail(
  regimeChange: { from: string; to: string; score: number } | null,
  signalFlips: SignalFlip[],
  compositeScore: number
): { subject: string; html: string } {
  const parts: string[] = [];

  if (regimeChange) {
    parts.push(`🔄 <strong>Regime Change:</strong> ${regimeChange.from} → ${regimeChange.to} (composite: ${compositeScore.toFixed(3)})`);
  }

  if (signalFlips.length > 0) {
    parts.push(`<br/><strong>Signal Flips:</strong>`);
    for (const flip of signalFlips) {
      const emoji = flip.direction === "bullish" ? "🟢" : "🔴";
      parts.push(`${emoji} <strong>${flip.signalName}</strong>: ${scoreLabel(flip.from)} → ${scoreLabel(flip.to)}`);
    }
  }

  const subject = regimeChange
    ? `⚡ Regime Change: ${regimeChange.from} → ${regimeChange.to}`
    : `📊 Signal Alert: ${signalFlips.length} signal${signalFlips.length > 1 ? "s" : ""} flipped`;

  const html = `
    <div style="font-family: -apple-system, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
      <h2 style="color: #1a1a2e; border-bottom: 2px solid #e94560; padding-bottom: 8px;">
        Macro Regime Dashboard — Alert
      </h2>
      <p style="color: #555; font-size: 14px;">
        ${new Date().toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" })}
      </p>
      <div style="background: #f8f9fa; border-radius: 8px; padding: 16px; margin: 16px 0;">
        <p style="margin: 0; font-size: 13px; color: #333;">
          <strong>Composite Score:</strong> ${compositeScore.toFixed(3)}
        </p>
      </div>
      ${parts.map(p => `<p style="margin: 8px 0; font-size: 14px; color: #333;">${p}</p>`).join("")}
      <hr style="border: none; border-top: 1px solid #eee; margin: 24px 0;" />
      <p style="font-size: 12px; color: #999;">
        This alert was generated by Macro Regime Dashboard. 
        To unsubscribe, reply to this email with "unsubscribe".
      </p>
    </div>
  `;

  return { subject, html };
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  const supabase = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
  );

  try {
    // Get the two most recent snapshots
    const { data: snapshots, error: snapErr } = await supabase
      .from("macro_snapshots")
      .select("id, composite_score, regime, signals, created_at")
      .order("created_at", { ascending: false })
      .limit(2);

    if (snapErr || !snapshots || snapshots.length < 2) {
      console.log("Not enough snapshots to compare:", snapErr?.message ?? `count=${snapshots?.length}`);
      return new Response(JSON.stringify({ status: "skipped", reason: "insufficient_snapshots" }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const [current, previous] = snapshots;
    const currentSignals = (current.signals ?? {}) as Record<string, number>;
    const previousSignals = (previous.signals ?? {}) as Record<string, number>;

    // Detect regime change
    let regimeChange: { from: string; to: string; score: number } | null = null;
    if (current.regime !== previous.regime) {
      regimeChange = {
        from: previous.regime ?? "unknown",
        to: current.regime ?? "unknown",
        score: current.composite_score ?? 0,
      };
      console.log(`Regime change detected: ${regimeChange.from} → ${regimeChange.to}`);
    }

    // Detect signal flips (score changed sign: bullish↔bearish, or to/from neutral)
    const signalFlips: SignalFlip[] = [];
    for (const [id, currentScore] of Object.entries(currentSignals)) {
      const prevScore = previousSignals[id];
      if (prevScore !== undefined && prevScore !== currentScore) {
        // Only alert on meaningful flips (crossing zero)
        const wasPositive = prevScore > 0;
        const wasNegative = prevScore < 0;
        const isPositive = currentScore > 0;
        const isNegative = currentScore < 0;

        if ((wasPositive && isNegative) || (wasNegative && isPositive) ||
            (wasPositive && currentScore === 0) || (wasNegative && currentScore === 0) ||
            (prevScore === 0 && (isPositive || isNegative))) {
          signalFlips.push({
            signalId: id,
            signalName: SIGNAL_NAMES[id] ?? id,
            from: prevScore,
            to: currentScore,
            direction: currentScore > prevScore ? "bullish" : "bearish",
          });
        }
      }
    }

    if (!regimeChange && signalFlips.length === 0) {
      console.log("No changes detected — no alerts to send.");
      return new Response(JSON.stringify({ status: "no_changes" }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    console.log(`Alerts: regime=${regimeChange ? "yes" : "no"}, signalFlips=${signalFlips.length}`);

    // Get active subscribers
    const { data: subscribers, error: subErr } = await supabase
      .from("alert_subscribers")
      .select("id, email, webhook_url, alert_regime_change, alert_signal_flips")
      .eq("active", true);

    if (subErr || !subscribers || subscribers.length === 0) {
      console.log("No active subscribers:", subErr?.message ?? "0 subscribers");
      // Still log the alert
      await supabase.from("alert_history").insert({
        alert_type: regimeChange ? "regime_change" : "signal_flip",
        details: { regimeChange, signalFlips, compositeScore: current.composite_score },
        subscribers_notified: 0,
      });
      return new Response(JSON.stringify({ status: "no_subscribers", regimeChange, signalFlips: signalFlips.length }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const compositeScore = current.composite_score ?? 0;
    let notified = 0;

    for (const sub of subscribers) {
      // Filter by preference
      const shouldNotify =
        (regimeChange && sub.alert_regime_change) ||
        (signalFlips.length > 0 && sub.alert_signal_flips);

      if (!shouldNotify) continue;

      // Send webhook if configured
      if (sub.webhook_url) {
        try {
          await fetch(sub.webhook_url, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              type: regimeChange ? "regime_change" : "signal_flip",
              timestamp: new Date().toISOString(),
              compositeScore,
              regimeChange,
              signalFlips: sub.alert_signal_flips ? signalFlips : [],
            }),
          });
          console.log(`Webhook sent to ${sub.webhook_url}`);
        } catch (e) {
          console.warn(`Webhook failed for ${sub.webhook_url}:`, e);
        }
      }

      // Send email via Lovable AI Gateway (using edge function invocation)
      if (sub.email) {
        const { subject, html } = formatAlertEmail(
          regimeChange && sub.alert_regime_change ? regimeChange : null,
          sub.alert_signal_flips ? signalFlips : [],
          compositeScore
        );

        try {
          const lovableApiKey = Deno.env.get("LOVABLE_API_KEY");
          if (lovableApiKey) {
            // Use Supabase's built-in email or a simple SMTP-less approach
            // For now, log the alert — email delivery requires email infrastructure setup
            console.log(`Alert email prepared for ${sub.email}: ${subject}`);
          }
        } catch (e) {
          console.warn(`Email alert failed for ${sub.email}:`, e);
        }
      }

      notified++;
    }

    // Log alert
    await supabase.from("alert_history").insert({
      alert_type: regimeChange ? "regime_change" : "signal_flip",
      details: { regimeChange, signalFlips, compositeScore },
      subscribers_notified: notified,
    });

    console.log(`Alert sent to ${notified} subscribers.`);

    return new Response(JSON.stringify({
      status: "alerts_sent",
      regimeChange,
      signalFlips: signalFlips.length,
      subscribersNotified: notified,
    }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (error) {
    const msg = error instanceof Error ? error.message : "Unknown error";
    console.error("check-alerts error:", msg);
    return new Response(JSON.stringify({ error: msg }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
